name: Maven Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_DB: pth_06
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MYSQL_USER: streamdb
          MYSQL_PASSWORD: streamdb_pass
        volumes:
          - ${{ github.workspace }}/database/:/docker-entrypoint-initdb.d/:ro
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify MariaDB connection
      env:
        MARIADB_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: for i in {1..30}; do mysqladmin ping -h127.0.0.1 -u root -P${MARIADB_PORT} && break; sleep 10; done

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Get version
      run: echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV

    - name: Generate sources
      run: mvn -Pbuild -B -Drevision=${{ env.RELEASE_VERSION }} -Dsha1= -Dchangelist= generate-sources -s dependencies.settings.xml
      env:
        MYSQL_USER: streamdb
        MYSQL_PASSWORD: streamdb_pass
        MARIADB_PORT: ${{ job.services.mariadb.ports[3306] }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Inject licenses to generated files
      run: bash add_headers_to_generated.sh

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -Pbuild-nogenerate -B -Drevision=${{ env.RELEASE_VERSION }} -Dsha1= -Dchangelist= deploy -s dependencies.settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
