name: Maven Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_USER: streamdb
          MYSQL_PASSWORD: streamdb_pass
        volumes:
          - ./database/journaldb.sql:/docker-entrypoint-initdb.d/journaldb.sql:ro
          - ./database/streamdb.sql:/docker-entrypoint-initdb.d/streamdb.sql:ro
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Get version
      run: echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV

    - name: Setup mariadb
      run: bash setup_mariadb.sh

    - name: Generate sources
      run: mvn -B -Drevision=${{ env.RELEASE_VERSION }} -Dsha1= -Dchangelist= generate-sources -s dependencies.settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Inject licenses to generated files
      run: bash add_headers_to_generated.sh

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B -Drevision=${{ env.RELEASE_VERSION }} -Dsha1= -Dchangelist= deploy -s dependencies.settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
