name: Upload Release to GitHub Packages

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set Revision
        id: revision
        run : |
          if [ "${{ github.repository_owner }}" = "teragrep" ]; then
            echo "revision=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "revision=${{ github.event.release.tag_name }}-${{ github.actor }}" >> $GITHUB_OUTPUT
          fi

      - name: Publish to GitHub Packages
        run: mvn --batch-mode -Drevision=${{ steps.revision.outputs.revision }} -Dsha1= -Dchangelist= -Dgithub.packages.url="https://maven.pkg.github.com/${{ github.repository_owner }}/pth_06" clean deploy -Ppublish-github-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}